backend:
  name: git-gateway
  branch: master

media_folder: "/static/images"

collections:
  - name: "Pages"
    label: "Pages"
    folder: "/pages"
    create: true
    fields:
      - {label: "Path", name: "path", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}