backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "images"

collections:
  - name: "Pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Items", name: "items", widget: "object", fields: [{label: "Item", name: "item", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Artist", name: "artist", widget: "string"}, {label: "Cover", name: "cover", widget: "image"}, {label: "Category", name: "category", widget: "string"}, {label: "Heading", name: "heading", widget: "string"}, {label: "Description", name: "description", widget: "string", required: false}, {label: "Year", name: "year", widget: "number"}, {label: "Genre", name: "genre", widget: "string"}, {label: "Video", name: "video", widget: "string", required: false}]}], required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}