backend:
  name: git-gateway
  branch: master

media_folder: "src/resources/images"
public_folder: "images"

collections:
  - name: "Pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}