backend:
  name: git-gateway
  branch: test

media_folder: static/images
public_folder: /images
display_url: https://www.nickveale.com

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/page/home.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Relative Path",
              name: "relpath",
              widget: "hidden",
              default: "../../..",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Meta Title",
              name: "metaTitle",
              widget: "string",
              hint: "Title that appears on the browser tab.",
            }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              hint:
                "SEO description that appears in search engines under the site
                name.",
            }
          - {
              label: "Keywords",
              name: "keywords",
              widget: "string",
              hint: "Search engine keywords (not essential)",
            }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Playlist", name: "playlist", widget: "string" }
          - {
              label: "Social",
              name: "social",
              widget: "list",
              fields:
                [
                  {
                    label: "Icon",
                    name: "icon",
                    widget: "select",
                    options: ["youtube", "twitch", "twitter", "facebook"],
                  },
                  { label: "Link", name: "link", widget: "string" },
                ],
              required: false,
            }
      - file: "src/pages/page/about.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Relative Path",
              name: "relpath",
              widget: "hidden",
              default: "../../..",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Order", name: "order", widget: "number" }
          - {
              label: "Meta Title",
              name: "metaTitle",
              widget: "string",
              hint: "Title that appears on the browser tab.",
            }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              hint:
                "SEO description that appears in search engines under the site
                name.",
            }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - {
              label: "Sections",
              name: "sections",
              widget: "object",
              fields:
                [
                  {
                    label: "Section",
                    name: "section",
                    widget: "list",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        {
                          label: "Description",
                          name: "description",
                          widget: "markdown",
                        },
                        {
                          label: "Playlist",
                          name: "playlist",
                          widget: "string",
                          required: false,
                        },
                      ],
                  },
                ],
              required: false,
            }
      - file: "src/pages/page/work.md"
        label: "Work"
        name: "work"
        fields:
          - {
              label: "Relative Path",
              name: "relpath",
              widget: "hidden",
              default: "../../..",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Order", name: "order", widget: "number" }
          - {
              label: "Meta Title",
              name: "metaTitle",
              widget: "string",
              hint: "Title that appears on the browser tab.",
            }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              hint:
                "SEO description that appears in search engines under the site
                name.",
            }
          - {
              label: "Items",
              name: "items",
              widget: "object",
              fields:
                [
                  {
                    label: "Item",
                    name: "item",
                    widget: "list",
                    fields:
                      [
                        { label: "Title", name: "title", widget: "string" },
                        { label: "Artist", name: "artist", widget: "string" },
                        {
                          label: "Cover",
                          name: "cover",
                          widget: "image",
                          required: false,
                        },
                        {
                          label: "Category",
                          name: "category",
                          widget: "string",
                        },
                        { label: "Heading", name: "heading", widget: "string" },
                        {
                          label: "Description",
                          name: "description",
                          widget: "markdown",
                          required: false,
                        },
                        { label: "Year", name: "year", widget: "number" },
                        { label: "Genre", name: "genre", widget: "string" },
                        {
                          label: "Video",
                          name: "video",
                          widget: "string",
                          required: false,
                        },
                        {
                          label: "Soundcloud",
                          name: "soundcloud",
                          widget: "string",
                          required: false,
                        },
                        {
                          label: "Spotify",
                          name: "spotify",
                          widget: "string",
                          required: false,
                        },
                        {
                          label: "Colour",
                          name: "colour",
                          widget: "string",
                          required: false,
                        },
                      ],
                  },
                ],
              required: false,
            }
      - file: "src/pages/page/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Order", name: "order", widget: "number" }
          - {
              label: "Meta Title",
              name: "metaTitle",
              widget: "string",
              hint: "Title that appears on the browser tab.",
            }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              hint:
                "SEO description that appears in search engines under the site
                name.",
            }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
